# Generated by Django 4.2.3 on 2023-07-31 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDMP_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 13, 50, 9, 581429, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='depositos',
            name='data_deposito',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 13, 50, 9, 582013, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='data_gasto',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 13, 50, 9, 581797, tzinfo=datetime.timezone.utc)),
        ),
    ]
