# Generated by Django 4.2.3 on 2023-08-01 13:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CDMP_APP', '0003_alter_categoria_data_criacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoModificaoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alteracao', models.DateTimeField(default=django.utils.timezone.now)),
                ('nome', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CDMP_APP.categoria')),
                ('gasto_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CDMP_APP.gasto')),
            ],
        ),
    ]
