# Generated by Django 4.2.3 on 2023-08-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDMP_APP', '0005_historicocliente_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='senha',
            field=models.CharField(default='', max_length=100),
        ),
    ]
