# Generated by Django 4.2.3 on 2023-09-19 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CDMP_APP', '0010_tetodegastos_abril_tetodegastos_agosto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CDMP_APP.cliente'),
        ),
    ]
