version: '3'
services:
  cdmp:
    build: .
    container_name: cdmp
    expose:
      - "8000"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
  
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./app/static:/app/static
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - cdmp
  
volumes:
  postgres_data:
    