version: '3'
services:
  cdmp:
    build: .
    container_name: cdmp
    volumes:
      - static_volume:/web/static
    expose:
      - "8000"
    command: bash app_build.sh
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=senha123
      - POSTGRES_USER=admin
      - POSTGRES_DB=cdmp
  
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=senha123
      - POSTGRES_USER=admin
      - POSTGRES_DB=cdmp
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    build:
      context: ./nginx
    container_name: nginx_container
    volumes:
      - static_volume:/web/static
    ports:
      - "80:80"
    depends_on:
      - cdmp
  
volumes:
  postgres_data:
  static_volume:
    