version: '3'
services:
  cdmp:
    build: .
    container_name: cdmp
    volumes:
      - ./app:/app
    ports:
      - "8000"
    command: bash app_build.sh
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
  
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    ports:
      - "5432"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./app/static:/app/static
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - cdmp
    