# Generated by Django 4.2.3 on 2023-07-31 13:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('data_criacao', models.DateTimeField(default=datetime.datetime(2023, 7, 31, 13, 48, 32, 189398))),
            ],
        ),
        migrations.CreateModel(
            name='Depositos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=50)),
                ('data_deposito', models.DateTimeField(default=datetime.datetime(2023, 7, 31, 13, 48, 32, 189960))),
            ],
        ),
        migrations.CreateModel(
            name='MetaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_meta', models.CharField(max_length=50)),
                ('valor_atual', models.FloatField()),
                ('icone', models.CharField(max_length=50)),
                ('valor_total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=50)),
                ('data_gasto', models.DateTimeField(default=datetime.datetime(2023, 7, 31, 13, 48, 32, 189747))),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CDMP_APP.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('foto', models.CharField(blank=True, default='default.jpg', max_length=100, null=True)),
                ('depositos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CDMP_APP.depositos')),
                ('gastos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CDMP_APP.gasto')),
                ('metas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CDMP_APP.metafinanceira')),
            ],
        ),
    ]
