# Generated by Django 4.2.3 on 2023-07-31 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CDMP_APP', '0002_alter_categoria_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='depositos',
            name='data_deposito',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='data_gasto',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
