# Generated by Django 4.2.3 on 2023-08-10 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CDMP_APP', '0006_cliente_senha'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gasto',
            new_name='Despesa',
        ),
        migrations.AlterModelOptions(
            name='despesa',
            options={'verbose_name': 'Despesa', 'verbose_name_plural': 'Despesas'},
        ),
        migrations.RenameField(
            model_name='despesa',
            old_name='data_gasto',
            new_name='data_despesa',
        ),
        migrations.AddField(
            model_name='historicocliente',
            name='deposito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CDMP_APP.depositos'),
        ),
        migrations.AddField(
            model_name='historicocliente',
            name='despesa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CDMP_APP.despesa'),
        ),
        migrations.AddField(
            model_name='historicocliente',
            name='meta_financeira',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CDMP_APP.metafinanceira'),
        ),
    ]
