# Generated by Django 4.2.3 on 2023-09-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDMP_APP', '0009_tetodegastos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tetodegastos',
            name='abril',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tetodegastos',
            name='agosto',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tetodegastos',
            name='dezembro',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tetodegastos',
            name='fevereiro',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tetodegastos',
            name='julho',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tetodegastos',
            name='junho',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tetodegastos',
            name='maio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tetodegastos',
            name='marco',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tetodegastos',
            name='novembro',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tetodegastos',
            name='outubro',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tetodegastos',
            name='setembro',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tetodegastos',
            name='janeiro',
            field=models.FloatField(default=0),
        ),
    ]
