# Generated by Django 4.2.3 on 2023-09-28 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CDMP_APP', '0012_remove_historicocliente_meta_financeira_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TetoDeGastosPorCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janeiro', models.FloatField(default=0)),
                ('fevereiro', models.FloatField(default=0)),
                ('marco', models.FloatField(default=0)),
                ('abril', models.FloatField(default=0)),
                ('maio', models.FloatField(default=0)),
                ('junho', models.FloatField(default=0)),
                ('julho', models.FloatField(default=0)),
                ('agosto', models.FloatField(default=0)),
                ('setembro', models.FloatField(default=0)),
                ('outubro', models.FloatField(default=0)),
                ('novembro', models.FloatField(default=0)),
                ('dezembro', models.FloatField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CDMP_APP.categoria')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CDMP_APP.cliente')),
            ],
        ),
    ]
