# Generated by Django 4.2.3 on 2023-09-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CDMP_APP', '0015_rename_abril_tetodegastosporcategoria_teto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicocliente',
            old_name='deposito',
            new_name='receita',
        ),
    ]
